"""Disclaimers cliniques standardisés du SDK.

Tout rapport généré par un module ClinVCF en mode ``clinical`` DOIT inclure :

1. Le disclaimer RUO (Research Use Only) — ClinVCF n'est pas un dispositif médical
2. Le disclaimer médical — ce rapport ne constitue pas une prescription
3. Le disclaimer de limitations méthodologiques — quoi a été (ou n'a pas été) évalué

Le SDK fournit ces textes en français et en anglais, et propose une fonction
``for_report`` qui assemble le disclaimer complet selon le contexte.
"""
from __future__ import annotations

from dataclasses import dataclass


_RUO_FR = (
    "ClinVCF est un logiciel destiné à la recherche et à l'aide à la décision "
    "(Research Use Only). Il n'est pas un dispositif médical au sens du "
    "Règlement (UE) 2017/745 et n'est pas destiné au diagnostic primaire."
)
_RUO_EN = (
    "ClinVCF is a research and decision support software (Research Use Only). "
    "It is not a medical device under EU Regulation 2017/745 and is not "
    "intended for primary diagnosis."
)

_NOT_PRESCRIPTION_FR = (
    "Ce rapport ne constitue pas une prescription. Les recommandations doivent "
    "être validées par un professionnel de santé en tenant compte du traitement "
    "envisagé, du contexte clinique, des co-médications, de la fonction rénale "
    "et hépatique, et des données biologiques du patient."
)
_NOT_PRESCRIPTION_EN = (
    "This report does not constitute a prescription. Recommendations must be "
    "reviewed by a qualified healthcare professional taking into account the "
    "intended treatment, the clinical context, co-medications, renal and "
    "hepatic function, and the patient's laboratory data."
)

_THIRD_PARTY_MODULE_FR = (
    "Ce rapport est généré par un module développé par un tiers indépendant. "
    "Fdevelopment, éditeur de la plateforme ClinVCF et du marketplace "
    "ClinStore, n'a pas développé ni audité scientifiquement ce module et "
    "décline toute responsabilité quant aux résultats produits. Le développeur "
    "du module est seul responsable de son contenu et de sa qualité scientifique."
)
_THIRD_PARTY_MODULE_EN = (
    "This report is generated by a module developed by an independent third "
    "party. Fdevelopment, publisher of the ClinVCF platform and the ClinStore "
    "marketplace, has not developed or scientifically audited this module and "
    "disclaims all liability for the results produced. The module's developer "
    "is solely responsible for its content and scientific quality."
)


@dataclass(frozen=True, slots=True)
class DisclaimerBlock:
    """Bloc de disclaimer : titre + corps + niveau de visibilité."""

    title: str
    body: str
    severity: str = "info"


class ClinicalDisclaimer:
    """Disclaimers cliniques standards du SDK.

    À utiliser via ``ClinicalDisclaimer.for_report(...)`` qui assemble la
    liste complète des disclaimers à afficher selon le contexte.
    """

    @staticmethod
    def ruo_notice(language: str = "fr") -> DisclaimerBlock:
        """Disclaimer Research Use Only."""
        if language == "en":
            return DisclaimerBlock(
                title="Research Use Only",
                body=_RUO_EN,
                severity="info",
            )
        return DisclaimerBlock(
            title="Usage Recherche Uniquement",
            body=_RUO_FR,
            severity="info",
        )

    @staticmethod
    def not_prescription(language: str = "fr") -> DisclaimerBlock:
        """Disclaimer médical — pas une prescription."""
        if language == "en":
            return DisclaimerBlock(
                title="Clinical disclaimer",
                body=_NOT_PRESCRIPTION_EN,
                severity="warning",
            )
        return DisclaimerBlock(
            title="Avertissement clinique",
            body=_NOT_PRESCRIPTION_FR,
            severity="warning",
        )

    @staticmethod
    def third_party_module(language: str = "fr") -> DisclaimerBlock:
        """Disclaimer pour les modules tiers (non-Fdevelopment)."""
        if language == "en":
            return DisclaimerBlock(
                title="Third-party module",
                body=_THIRD_PARTY_MODULE_EN,
                severity="warning",
            )
        return DisclaimerBlock(
            title="Module tiers",
            body=_THIRD_PARTY_MODULE_FR,
            severity="warning",
        )

    @staticmethod
    def methodology_limitations(
        notes: list[str],
        language: str = "fr",
    ) -> DisclaimerBlock:
        """Disclaimer méthodologique reprenant les limitations détectées.

        Args:
            notes: Liste des limitations à présenter (ex. "CNV/SV non évalués",
                "HLA non typé depuis VCF").
            language: "fr" ou "en".
        """
        if not notes:
            notes = (
                ["No methodological limitations detected."]
                if language == "en"
                else ["Aucune limitation méthodologique détectée."]
            )

        bullet = "• "
        body = "\n".join(f"{bullet}{note}" for note in notes)
        if language == "en":
            return DisclaimerBlock(
                title="Methodological limitations",
                body=body,
                severity="warning",
            )
        return DisclaimerBlock(
            title="Limitations méthodologiques",
            body=body,
            severity="warning",
        )

    @staticmethod
    def for_report(
        *,
        language: str = "fr",
        report_type: str = "clinical",
        is_third_party_module: bool = False,
        methodology_notes: list[str] | None = None,
    ) -> list[DisclaimerBlock]:
        """Assemble la liste complète des disclaimers pour un rapport.

        Args:
            language: "fr" ou "en".
            report_type: "clinical" inclut tous les disclaimers obligatoires ;
                "research" est plus léger ; "demo" est minimal.
            is_third_party_module: True si le module n'est pas édité par
                Fdevelopment (ajoute le disclaimer tiers).
            methodology_notes: Liste des limitations méthodologiques détectées
                pendant l'analyse (sera intégrée dans le bloc dédié).

        Returns:
            Liste ordonnée de ``DisclaimerBlock`` à afficher dans le rapport.
            L'ordre suit la convention de lecture : RUO en premier
            (positionnement légal), méthodologie ensuite (technique), médical
            en dernier (le plus important pour le clinicien).
        """
        if report_type == "demo":
            return [ClinicalDisclaimer.ruo_notice(language)]

        blocks = [ClinicalDisclaimer.ruo_notice(language)]

        if is_third_party_module:
            blocks.append(ClinicalDisclaimer.third_party_module(language))

        if report_type == "clinical":
            blocks.append(
                ClinicalDisclaimer.methodology_limitations(
                    methodology_notes or [], language
                )
            )
            blocks.append(ClinicalDisclaimer.not_prescription(language))

        return blocks
